blog/urls.py
#from blog.viewsets import ArticleViewSet
#from rest_framework.routers import DefaultRouter
from . import views
from django.urls import path

#router = DefaultRouter()
#router.register(r'articles', ArticleViewSet, basename='article')
#urlpatterns = router.urls
urlpatterns = [
    path('', views.BlogList.as_view(), name='home'),
    path('blog/<int:pk>', views.BlogDetail.as_view(), name='blog_detail'),
    path('lottery', views.get_random),
]

djdemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('news/', include('news.urls')),
    path('ticketcrawler/', include('ticketcrawler.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from . import views
from rest_framework.routers import DefaultRouter
from django.urls import path, include

#from rest_framework import renderers
#from rest_framework.urlpatterns import format_suffix_patterns


#router = DefaultRouter()

#router.register(r'report', views.ReportList, basename = 'report')
#urlpatterns = router.urls

#report = views.ReportViewSet.as_view({
#	'get': 'list',
#	'post': 'create'
#})
urlpatterns = [
	path('', views.ReportList.as_view(), name='report'),
	path('render_js/', views.render_js, name='render_js'),
	path('report_json/', views.report_lst, name='report_json'),
	path('report_json/<int:pk>', views.report_detail, name='report_detail'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse #used to generate URLs by reverting the URL pattern

# Create your models here.

STATUS = (
	(0, "Draft"),
	(1, "Publish")
)
class Tag(models.Model):
	"""Model representing a blog tags."""
	name = models.CharField(max_length=200, help_text='Enter a blog tag (e.g. science)')

	def __str__(self):
	        """String for representing the Model object."""
        	return self.name

class Blog(models.Model):
	title = models.CharField(max_length=200, unique=True)
	author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
	updated_on = models.DateTimeField(auto_now= True)
	content = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	status = models.IntegerField(choices=STATUS, default=0)
	tag = models.ManyToManyField(Tag, help_text='Select a tag for this book')
	class Meta:
        	ordering = ['-created_on']

	def __str__(self):
        	return self.title

# ----------- Add below for modification ------------------------------------    
	def get_absolute_url(self):
        	"""Returns the url to access a detail record for this blog"""
        	return reverse('blog_detail', kwargs={'pk': self.pk})

	def display_tag(self):
	        """ Create a string for the Tag. This is required to display tag in Admin."""
        	return ', '.join(tag.name for tag in self.tag.all()[:3])
	display_tag.short_description = 'Tag'

news/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
	name = models.CharField(max_length=100)

class Report(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField(blank=True)
	created_on = models.DateTimeField(auto_now= True)
	author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Blog


# Create your views here.
class BlogList(generic.ListView):
    queryset = Blog.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'

    
class BlogDetail(generic.DetailView):
    model = Blog
    template_name = 'blog_detail.html'


def get_random(request):
	luckynum = gather_nums()
	# Pass the imported dict to the templatehttps://github.com/nova1987a
	return  render(request, 'lottery.html', {'r': luckynum})


## New web scraping method , read a single file and generate random numbers
import json

## Open the record file
def gather_nums():
	input_file = '/home/w9saka5ulbu0/public_html/djdemo/blog/frequent_nums.dat'
	with open(input_file, "r") as f:
		data = f.read()
		nums = json.loads(data)

	select_lst = []
	select_lst.append(nums[0])
	## Select if diff of 2 number is equal or larger than 4
	for i in range(len(nums)):
		if nums[i]-select_lst[len(select_lst)-1] >= 4:
			select_lst.append(nums[i])

	random_lst = []
	for j in range(len(select_lst)-1):
		random_num = randrange(select_lst[j], select_lst[j+1])
		random_lst.append(random_num)
	
	final_dict = {"Most frequent number(s)":[], "Lucky number(s)":[]}
	final_dict.update({"Most frequent number(s)":select_lst, "Lucky number(s)":random_lst})
	return final_dict

news/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from rest_framework.views import APIView
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from .serializers import ReportSerializer
from .models import Report
from django.views.decorators.csrf import csrf_exempt 


# Create your views here.


class ReportAPIView(APIView):
	def get_object(self, pk):
		report = get_object_or_404(Report, pk=pk)
		return report
	def get(self, request, *args, **kwargs):
		pk = self.kwargs['pk']
		report = self.get_object(pk)
		serializer = ReportSerializer(report)
		return Response(serializer.data)



class ReportList(APIView):
	renderer_classes = [TemplateHTMLRenderer]
	template_name = 'report_api.html'

	def get(self, request):
		queryset = Report.objects.all()
		return Response({'reports': queryset})

@csrf_exempt
def report_lst(request):
	"""A view returning all in list """
	reports = Report.objects.all()
	serializer = ReportSerializer(reports, many=True)
	serializer_data = {"data": serializer.data}
	return JsonResponse(serializer_data, safe=False)

def report_detail(request, pk):
	""" Retrive a code of report"""
	try:
		report = Report.objects.get(pk=pk)
	except Report.DoesNotExist:
		return HttpResponse(status=404)

	serializer = ReportSerializer(report)
	return JsonResponse(serializer.data)

def render_js(request):
	return render(request, 'json2js.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Djdemo site</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Django BLOGs</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
			            <li class="nav-item dropdown">
				            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">News</a>
				            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
		                        <li><a class="dropdown-item" href="{% url 'report' %}">Report</a></li>
                		        <li><a class="dropdown-item" href="{% url 'report_json' %}">Report in JSON</a></li>
		                        <li><a class="dropdown-item" href="{% url 'render_js' %}">Report_JS</a></li>
				            </ul>
			            </li>
                        <li class="nav-item">
                            <a class="nav-link" href="lottery">Get Lucky No.</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block header %} 
        <header class="bg-primary">
            <div class="overlay "></div>
            <div class="container">
                <div class="row">
                     <div class=" col-md-8 col-md-10 mx-auto">
                         <div class="site-heading">
                            <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my Demo Blog </h3>
                            <p class="text-light">Focus on ...</p>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        
        {% block index %}
        <!-- Content Goes here -->
        {% endblock index %}
                
        <!-- Footer -->
        <footer class="p-3 mb-2 bg-primary text-white">
            <center><h3 id="about">About</h3></center>
            <p class="m-0 text-light text-center ">This is a demo site built with Django framework, hope you enjoy it!</p>
            <p class="m-0 text-light text-center ">Copyleft &copy; balajan blogs, refer to: <a class="text-light" href="https://djangocentral.com/building-a-blog-application-with-django/">Django Central</a></p>
        </footer>
    </body>
</html>

templates/blog_detail.html
{% extends "base.html" %}
{% block index %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ blog.author }} | {{ blog.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}



{% block index %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 left">
            <!-- Blog Entries Column -->
                {% for blog in blog_list %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ blog.title }}</h2>
                        <p class="card-text text-muted h6">{{ blog.author }} | {{ blog.created_on}} </p>
                        <p class="card-text">{{blog.content|slice:":200" | safe}}</p>
                        <p class="card-text text-muted h6">Tags: {{blog.display_tag}}</p>
                        <a href="{{ blog.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-4 float-right ">
                {% block sidebar %}
                <!-- Sidebar Widgets Column -->
	            <div class="card my-4">
	                <h5 class="card-header">About Us</h5>
                    <div class="card-body">
                        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django'..!</p>
                        <a href="https://www.djangoproject.com/" class="btn btn-danger">Know more!</a>
                    </div>
                </div>
                {% endblock sidebar %}
                
            </div>
        </div>
    </div>
{% endblock %}

  

templates/json2js.html
{% extends "base.html" %}
{% block index %}
<div class="row pt-3 ps-3">
	<section></section>
	<script type="text/javaScript">
		var section = document.querySelector("section");

		var requestURL = "http://djdemo.guosi.site/news/report_json/";
		var request = new XMLHttpRequest();
		request.open("GET", requestURL);

		request.responseType = "json";
		request.send();
		
		request.onload = function () {
			var mainArticles = request.response;
			showArticles(mainArticles);	// function showTitles
		};
		
		function showArticles(jsonObj) {
			var articles = jsonObj["data"];

			for (i = 0; i < articles.length; i++) {
				var myArticle = document.createElement("article");
				var myH2 = document.createElement("h2");
				var myPara1 = document.createElement("p");
				var myPara2 = document.createElement("p");
				
				// Add title and created_on
				myH2.textContent = articles[i].title;
				myPara1.textContent = "Created on: " + articles[i].created_on;

				// Add content
				myPara2.textContent = "Content: " + articles[i].content;

				myArticle.appendChild(myH2);
				myArticle.appendChild(myPara1);
				myArticle.appendChild(myPara2);

				section.appendChild(myArticle);
			}
		}
	</script>
</div>
{% endblock %}

templates/lottery.html
{% extends "base.html" %}

{% block index %}
<div class="container  my-3">
 <div class="row">
  <div class="col-lg-6 mx-auto my-auto my-2">
   <div class="card" style="width:20 rem;">
    <div class="card-body">
	<p class="lead text-center text-secondary"> Let's get lucky numbers!</p>
	<hr>
	{% for key, values in r.items %}
    	<h5 class="card-title text-center">{{key}}</h5>
	<!--h6 class="card-subtitle muted text-center">Let's get some lucky numbers! :-)</h6-->
	<div class="row justify-content-md-center alert alert-primary">
		{%  for value in values %}
		 	<div class="col-2 ">{{ value }}</div>
		{% endfor %}
	</div>
        {% endfor %}
    </div>
   </div>
  </div>
 </div>
</div>

{% endblock %}

templates/report_api.html
{% extends "base.html" %}
{% block index %}
<ul>
	<div class="col-md-8 mt-3 left">
	{% for report in reports %}
		<li>{{ report.title }}</li>
		<p>{{ report.created_on }}</p>
		<p>{{ report.content }}</p>
	{% endfor %}
	</div>
</ul>
{% endblock %}